from .cutout import Cutout
from .has import HaS
from .gridmask import *
from .randomerasing import RandomErasing
from .blur import Blur
from .equalize import Equalize
from .PatchGaussian import AddPatchGaussian
from .shearX import ShearX
from .rotate import Rotate
# from .function import *
from .brightness import Brightness
from .color import Color
from .contrast import Contrast
from .solarize import Solarize
from .invert import Invert
from .posterize import Posterize
from .sharpness import Sharpness
from .augmentation import AutoContrast#Cutout
from .policy import Policy
from .randaugment import RandAugment
from .randomerasing_fixed import RandomErasing_fixed
from .translateX import TranslateX
from .mixup import *
from .cutmix import *